#config_version=5
hardware:
    platform: p_roc
    driverboards: pdb

keyboard:
    q:
        switch: s_left_flipper
    p:
        switch: s_right_flipper
    s:
        switch: s_start
    l:
        switch: s_launch_button
    x:
        switch: s_scoop
    1:
        switch: s_pop_left
    2: 
        switch: s_pop_right
    3:
        switch: s_pop_middle

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger



modes:
    - base
    - scoop_multiball

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3
        eject_coil: c_trough_eject
        tags: trough, home, drain   
        eject_targets: bd_plunger
    bd_plunger:
        ball_switches: s_plunger_lane
        eject_coil: c_plunger
        player_controlled_eject_event: s_launch_button_active
    bd_scoop:
        ball_switches: s_scoop
        eject_coil: c_scoop
        eject_timeouts: 2s

autofire_coils:
    ac_pop_left:
        coil: c_pop_left
        switch: s_pop_left
    ac_pop_right:
        coil: c_pop_right
        switch: s_pop_right
    ac_pop_middle:
        coil: c_pop_middle
        switch: s_pop_middle
    ac_slingshot_left:
        coil: c_slingshot_left
        switch: s_slingshot_left
    ac_slingshot_right:
        coil: c_slingshot_right
        switch: s_slingshot_right

switches:
    s_left_flipper:
        number: SD16
        tags: left_flipper
    s_right_flipper:
        number: SD20
        tags: right_flipper
    s_trough1:
        number: SD8
    s_trough2:
        number: SD9
    s_trough3:
        number: SD10
    s_start:
        number: SD18
        tags: start
    s_pop_left:
        number: SD13
    s_pop_right:
        number: SD14
    s_pop_middle:
        number: SD15
    s_slingshot_left:
        number: SD12
    s_slingshot_right:
        number: SD11
    s_plunger_lane:
        number: 0/0
    s_launch_button:
        number: SD19
    s_scoop:
        number: SD21
        type: NC

#I need to add a plunger switch!

coils:
    c_flipper_left_main:
        number: A0-B1-2
        default_pulse_ms: 25
    c_flipper_left_hold:
        number: A0-B1-3
        allow_enable: true
    c_flipper_right_main:
        number: A0-B1-0
        default_pulse_ms: 25
    c_flipper_right_hold:
        number: A0-B1-1
        allow_enable: yes
    c_trough_eject:
        number: A0-B1-7
        default_pulse_ms: 20
    c_pop_left:
        number: A0-B0-5
    c_pop_right:
        number: A0-B0-6
    c_pop_middle:
        number: A0-B0-7
    c_slingshot_left:
        number: A0-B1-5
    c_slingshot_right:
        number: A0-B1-4
    c_plunger:
        number: A0-B1-6
    c_scoop:
        number: A0-B0-4



virtual_platform_start_active_switches:
    s_trough1
    s_trough2
    s_trough3

dmds:
  dmd:
    shades: 16
    fps: 24

window:
  width: 600
  height: 200
  title: Mission Pinball Framework - Demo Man
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window

displays:
  window:
    width: 600
    height: 200
  dmd:
    width: 128
    height: 32
    default: true
     
slides:
    welcome_slide:
        widgets:
            - type: text
              text: "THE HEIST"
    attract_started:
        widgets:
            - type: text
              text: THE HEIST
widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
    
slide_player:
   init_done: welcome_slide
   mode_attract_started: attract_started